name: Run Flask App on GitHub

on:
  push:
    branches:
      - main

jobs:
  run-flask:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt

    - name: Install Ngrok
      run: |
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt update && sudo apt install ngrok

    - name: Run Flask App with Ngrok
      run: |
        export FLASK_APP=app.py
        nohup flask run --host=0.0.0.0 --port=8080 &
        nohup ngrok http 8080 &
        sleep 10
        curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'